# Generated by Django 4.2.5 on 2023-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.ManyToManyField(related_name='contact_groups', to='contacts.contact')),
            ],
        ),
    ]
