# Generated by Django 4.2.5 on 2023-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='contacts_book',
            new_name='contact_book',
        ),
        migrations.AlterField(
            model_name='events',
            name='dat_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
